lexicon = {

    # What to do with 'whether', 'if', wh-ever words?
    'wh_complementizers': {
        'what', 'who', 'how', 'why', 'where', 'which', 'whose', 'whom'
    },

    'all_complementizers': {
        'what', 'who', 'how', 'why', 'where', 'which', 'whose', 'whom', 'that', 'to'
    },

    'extraposing_verbs': {
        'appear', 'appears', 'appeared', 'appearing',
        # 'be', 'am', "'m", 'is', "'s", 'are', "'re", 'been', 'being',
        'follow', 'follows', 'following', 'followed',
        'seem', 'seems', 'seemed', 'seeming',
        'show', 'shows', 'showed', 'showing', 'shown'
    },

    # longman p 714
    'extraposed_to_verbs': {
        'help', 'helps', 'helped', 'helping',
        'take', 'takes', 'took', 'taken', 'taking',

    },

    # pp. 672-673 in longman
    'extraposing_adjectives': {
        'clear', 'likely', 'unlikely', 'possible', 'impossible',
        'true',

        'accepted', 'apparent', 'certain', 'clear', 'correct',
        'doubtful', 'evident', 'false', 'inevitable', 'likely',
        'unlikely', 'obvious', 'plain', 'possible', 'impossible',
        'probable', 'right', 'true', 'well-known',

        'acceptable', 'unacceptable', 'amazing', 'anomalous',
        'annoying', 'appropriate', 'astonishing', 'awful', 'inconceivable',
        'conceivable', 'curious', 'disappointing',
        'dreadful', 'embarrassing', 'extraordinary', 'unfortunate', 'fortunate',
        'frightening', 'funny', 'good',
        'great', 'horrible', 'incidental', 'incredible', 'indisputable',
        'interesting', 'ironic', 'irritating',
        'unlucky', 'lucky', 'natural', 'neat', 'nice', 'notable', 'noteworthy',
        'noticeable', 'odd', 'okay',
        'paradoxical', 'peculiar', 'preferable', 'ridiculous', 'sad',
        'sensible', 'shocking', 'silly', 'strange',
        'stupid', 'sufficient', 'surprising', 'tragic', 'untypical', 'typical',
        'unfair', 'understandable', 'unthinkable', 'unusual',
        'upsetting', 'wonderful',

        'advisable', 'critical', 'crucial', 'desirable', 'essential',
        'fitting', 'imperative', 'important', 'necessary', 'obligatory',
        'vital'

    },

    'copular_verbs': {
        'be', 'am', 'are', 'is', 'was', 'were', 'been', 'being',
        'seem', 'seems', 'seemed', 'seeming',
        'appear', 'appears', 'appeared', 'appearing',
        'keep', 'keeps', 'kept', 'keeping',
        'remain', 'remains', 'remained', 'remaining',
        'stay', 'stays', 'stayed', 'staying',
        'become', 'becomes', 'became', 'becoming',
        'get', 'gets', 'got', 'getting', 'gotten',
        'go', 'goes', 'went', 'going', 'gone',
        'grow', 'grows', 'grew', 'growing', 'grown',
        'prove', 'proves', 'proved', 'proving', 'proven',
        'come', 'comes', 'came', 'coming',
        'turn', 'turns', 'turned', 'turning',
        'look', 'looks', 'looked', 'looking',
        'sound', 'sounds', 'sounded', 'sounding'},

    'phrasal_copular_verbs': {
        (('turn', 'turns', 'turned', 'turning'), 'out'),
        (('end', 'ends', 'ended', 'ending'), 'up'),
        (('wind', 'winds', 'wound', 'winding'), 'up')
    },
    # modal types
    'necessity_modals': [['must'], ['should'], ['had', 'better'], ["'d", 'better'], ['better'], ['have', 'to'],
                         ['need', 'to'], ['ought', 'to'], ["'s", 'got', 'to'], ["'ve", 'got', 'to'],
                         ['have', 'got', 'to'], ['be', 'supposed', 'to'], ["'m", 'supposed', 'to'],
                         ['am', 'supposed', 'to'], ['is', 'supposed', 'to'], ["'s", 'supposed', 'to'],
                         ['are', 'supposed', 'to'], ["'re", 'supposed', 'to'], ['was', 'supposed', 'to'],
                         ['were', 'supposed', 'to'], ['being', 'supposed', 'to'], ['has', 'got', 'to'],
                         ['been', 'supposed', 'to'], ['be', 'to'], ['is', 'to'], ["'s", 'to'], ['am', 'to'],
                         ["'m", 'to'], ['are', 'to'], ["'re", 'to'], ['was', 'to'], ['were', 'to'], ['been', 'to'],
                         ['being', 'to']],
    'possibility_modals': [['can'], ['could'], ['may'], ['might'], ['is', 'able', 'to'], ["'s", 'able', 'to'],
                           ['am', 'able', 'to'], ["'m", 'able', 'to'], ['be', 'able', 'to'], ['are', 'able', 'to'],
                           ["'re", 'able', 'to'], ['was', 'able', 'to'], ['were', 'able', 'to'],
                           ['is', 'able', 'to'], ["being", 'able', 'to'], ['been', 'able', 'to'],
                           ['be', 'permitted', 'to'], ['is', 'permitted', 'to'], ["'s", 'permitted', 'to'],
                           ['am', 'permitted', 'to'], ["'m", 'permitted', 'to'], ['are', 'permitted', 'to'],
                           ["'re", 'permitted', 'to'], ['was', 'permitted', 'to'], ['were', 'permitted', 'to'],
                           ['been', 'permitted', 'to'], ['being', 'permitted', 'to'], ['be', 'allowed', 'to'],
                           ['is', 'allowed', 'to'], ["'s", 'allowed', 'to'], ['am', 'allowed', 'to'],
                           ["'m", 'allowed', 'to'], ['are', 'allowed', 'to'], ["'re", 'allowed', 'to'],
                           ['was', 'allowed', 'to'], ['were', 'allowed', 'to'], ['been', 'allowed', 'to'],
                           ['being', 'allowed', 'to']],
    'prediction_modals': [['will'], ['would'], ['shall'], ['sha'], ['wo'], ['is', 'going', 'to'], ["'s", 'going', 'to'],
                          ['are', 'going', 'to'], ["'re", 'going', 'to'], ['am', 'going', 'to'],
                          ["'m", 'going', 'to'], ['be', 'going', 'to'], ['was', 'going', 'to'],
                          ['were', 'going', 'to'], ['been', 'going', 'to'], ['be', 'about' 'to'],
                          ['am', 'about', 'to'], ['are', 'about', 'to'], ['is', 'about', 'to'],
                          ["'m", 'about', 'to'], ["'s", 'about', 'to'], ["'re", 'about', 'to'],
                          ['being', 'about', 'to'], ['was', 'about', 'to'], ['were', 'about', 'to'],
                          ['being', 'about', 'to']],

    # multiword subordinating conjunctions
    'subordinating_conjunctions_multi': [['as', 'long', 'as'], ['as', 'soon', 'as'], ['given', 'that'],
                                         ['on', 'condition', 'that'], ['provided', 'that'], ['except', 'that'],
                                         ['in', 'that'], ['in', 'order', 'that'], ['so', 'that'], ['such', 'that'],
                                         ['as', 'if'], ['as', 'though'], ['even', 'if'], ['even', 'though']],
    # noun types
    'noun_types': {
        'communication': {'announcement', 'announcements', 'comment', 'comments', 'declaration', 'declarations',
                          'demand', 'demands', 'hint', 'hints', 'news', 'promise', 'promises', 'proposal', 'proposals',
                          'proposition', 'propositions', 'recommendation', 'recommendations', 'remark', 'remarks',
                          'report', 'reports', 'requirement', 'requirements', 'warning', 'warnings'},

        'attitudinal': {'fear', 'fears', 'ground', 'grounds', 'hope', 'hopes', 'reason', 'reasons', 'thought',
                        'thoughts', 'view', 'views'},

        'factive': {'assertion', 'assertions', 'conclusion', 'conclusions', 'conviction', 'convictions', 'discoveries',
                    'discovery', 'doubt', 'doubts', 'fact', 'facts', 'knowledge', 'knowledges', 'observation',
                    'observations', 'principle', 'principles', 'realisation', 'realisations', 'realization',
                    'realizations', 'result', 'results', 'statement', 'statements'},

        'likelihood': {'assumption', 'assumptions', 'belief', 'beliefs', 'claim', 'claims', 'contention', 'contentions',
                       'expectation', 'expectations', 'feeling', 'feelings', 'hypotheses', 'hypothesis', 'idea',
                       'ideas', 'implication', 'implications', 'impression', 'impressions', 'indication', 'indications',
                       'notion', 'notions', 'opinion', 'opinions', 'perception', 'perceptions', 'possibilities',
                       'possibility', 'prediction', 'predictions', 'presumption', 'presumptions', 'probabilities',
                       'probability', 'rumor', 'rumors', 'sense', 'senses', 'sign', 'signs', 'suggestion',
                       'suggestions', 'suspicion', 'suspicions', 'theses', 'thesis'},

        'stance': {'abilities', 'ability', 'agreement', 'agreements', 'attempt', 'attempts', 'authorities', 'authority',
                   'battle', 'battles', 'bid', 'bids', 'capacities', 'capacity', 'chance', 'chances', 'commitment',
                   'commitments', 'confidence', 'confidences', 'deal', 'deals', 'decision', 'decisions', 'desire',
                   'desires', 'determination', 'determinations', 'duties', 'duty', 'effort', 'efforts', 'failure',
                   'failures', 'freedom', 'freedoms', 'inabilities', 'inability', 'incentive', 'incentives',
                   'inclination', 'inclinations', 'intention', 'intentions', 'invitation', 'invitations', 'obligation',
                   'obligations', 'opportunities', 'opportunity', 'permission', 'permissions', 'plan', 'plans', 'plot',
                   'plots', 'potential', 'potentials', 'power', 'powers', 'promise', 'promises', 'proposal',
                   'proposals', 'readiness', 'refusal', 'refusals', 'reluctance', 'reluctances', 'responsibilities',
                   'responsibility', 'right', 'rights', 'scheme', 'schemes', 'temptation', 'temptations', 'tendencies',
                   'tendency', 'threat', 'threats', 'willingness', 'wish', 'wishes'}
    },


    # verb types
    'verb_types': {
        'communication': {'add', 'adds', 'added', 'adding',
                          'advise', 'advises', 'advised', 'advising',
                          'allege', 'alleges', 'alleged', 'alleging',
                          'announce', 'announces', 'announced', 'announcing',
                          'answer', 'answers', 'answered', 'answering',
                          'argue', 'argues', 'argued', 'arguing',
                          'ask', 'asks', 'asked', 'asking',
                          'assert', 'asserts', 'asserted', 'asserting',
                          'assure', 'assures', 'assured', 'assuring',
                          'charge', 'charges', 'charged', 'charging',
                          'claim', 'claims', 'claimed', 'claiming',
                          'comment', 'comments', 'commented', 'commenting',
                          'confess', 'confesses', 'confessed', 'confessing',
                          'confide', 'confides', 'confided', 'confiding',
                          'contend', 'contends', 'contended', 'contending',
                          'convey', 'conveys', 'conveyed', 'conveying',
                          'convince', 'convinces', 'convinced', 'convincing',
                          'declare', 'declares', 'declared', 'declaring',
                          'demand', 'demands', 'demanded', 'demanding',
                          'deny', 'denies', 'denied', 'denying',
                          'emphasize', 'emphasizes', 'emphasized', 'emphasizing',
                          'explain', 'explains', 'explained', 'explaining',
                          'express', 'expresses', 'expressed', 'expressing',
                          'forewarn', 'forewarns', 'forewarned', 'forewarning',
                          'grant', 'grants', 'granted', 'granting',
                          'hear', 'hears', 'heard', 'hearing',
                          'hint', 'hints', 'hinted', 'hinting',
                          'hold', 'holds', 'holded', 'holding',
                          'imply', 'implies', 'implied', 'implying',
                          'inform', 'informs', 'informed', 'informing',
                          'insist', 'insists', 'insisted', 'insisting',
                          'maintain', 'maintains', 'maintained', 'maintaining',
                          'mention', 'mentions', 'mentioned', 'mentioning',
                          'mutter', 'mutters', 'muttered', 'muttering',
                          'notify', 'notifies', 'notified', 'notifying',
                          'order', 'orders', 'ordered', 'ordering',
                          'persuade', 'persuades', 'persuaded', 'persuading',
                          'petition', 'petitions', 'petitioned', 'petitioning',
                          'phone', 'phones', 'phoned', 'phoning',
                          'pray', 'prays', 'prayed', 'praying',
                          'proclaim', 'proclaims', 'proclaimed', 'proclaiming',
                          'promise', 'promises', 'promised', 'promising',
                          'propose', 'proposes', 'proposed', 'proposing',
                          'protest', 'protests', 'protested', 'protesting',
                          'reassure', 'reassures', 'reassured', 'reassuring',
                          'recommend', 'recommends', 'recommended', 'recommending',
                          'remark', 'remarks', 'remarked', 'remarking',
                          'remind', 'reminds', 'reminded', 'reminding',
                          'reply', 'replies', 'replied', 'replying',
                          'report', 'reports', 'reported', 'reporting',
                          'respond', 'responds', 'responded', 'responding',
                          'reveal', 'reveals', 'revealed', 'revealing',
                          'say', 'says', 'said', 'saying',
                          'shout', 'shouts', 'shouted', 'shouting',
                          'state', 'states', 'stated', 'stating',
                          'stress', 'stresses', 'stressed', 'stressing',
                          'suggest', 'suggests', 'suggested', 'suggesting',
                          'swear', 'swears', 'swore', 'swearing', 'sworn',
                          'teach', 'teaches', 'taught', 'teaching',
                          'telephone', 'telephones', 'telephoned', 'telephoning',
                          'tell', 'tells', 'told', 'telling',
                          'urge', 'urges', 'urged', 'urging',
                          'vow', 'vows', 'vowed', 'vowing',
                          'warn', 'warns', 'warned', 'warning',
                          'whisper', 'whispers', 'whispered', 'whispering',
                          'wire', 'wires', 'wired', 'wiring',
                          'write', 'writes', 'wrote', 'writing'},

        'attitude': {'accept', 'accepts', 'accepted', 'accepting',
                     'admit', 'admits', 'admitted', 'admiting',
                     'agree', 'agrees', 'agreed', 'agreeing',
                     'anticipate', 'anticipates', 'anticipated', 'anticipating',
                     'boast', 'boasts', 'boasted', 'boasting',
                     'complain', 'complains', 'complained', 'complaining',
                     'concede', 'concedes', 'conceded', 'conceding',
                     'cry', 'cries', 'cried', 'crying',
                     'dream', 'dreams', 'dreamed', 'dreaming', 'dreamt',
                     'ensure', 'ensures', 'ensured', 'ensuring',
                     'expect', 'expects', 'expected', 'expecting',
                     'fancy', 'fancies', 'fancied', 'fancying',
                     'fear', 'fears', 'feared', 'fearing',
                     'feel', 'feels', 'felt', 'feeling',
                     'foresee', 'foresees', 'foresaw', 'foreseeing', 'foreseen',
                     'forget', 'forgets', 'forgot', 'forgeting',
                     'guarantee', 'guarantees', 'guaranteed', 'guaranteeing',
                     'hope', 'hopes', 'hoped', 'hoping',
                     'mind', 'minds', 'minded', 'minding',
                     'prefer', 'prefers', 'preferred', 'prefering',
                     'pretend', 'pretends', 'pretended', 'pretending',
                     'reflect', 'reflects', 'reflected', 'reflecting',
                     'require', 'requires', 'required', 'requiring',
                     'resolve', 'resolves', 'resolved', 'resolving',
                     'trust', 'trusts', 'trusted', 'trusting',
                     'wish', 'wishs', 'wished', 'wishing',
                     'worry', 'worries', 'worried', 'worrying'},

        'factive': {'acknowledge', 'acknowledges', 'acknowledged', 'acknowledging',
                    'affirm', 'affirms', 'affirmed', 'affirming',
                    'ascertain', 'ascertains', 'ascertained', 'ascertaining',
                    'calculate', 'calculates', 'calculated', 'calculating',
                    'certify', 'certifies', 'certified', 'certifying',
                    'check', 'checks', 'checked', 'checking',
                    'conclude', 'concludes', 'concluded', 'concluding',
                    'confirm', 'confirms', 'confirmed', 'confirming',
                    'decide', 'decides', 'decided', 'deciding',
                    'deem', 'deems', 'deemed', 'deeming',
                    'demonstrate', 'demonstrates', 'demonstrated', 'demonstrating',
                    'determine', 'determines', 'determined', 'determining',
                    'discover', 'discovers', 'discovered', 'discovering',
                    'find', 'finds', 'found', 'finding',
                    'know', 'knows', 'knowed', 'knowing',
                    'learn', 'learns', 'learned', 'learning', 'learnt',
                    'mean', 'means', 'meaned', 'meaning',
                    'note', 'notes', 'noted', 'noting',
                    'notice', 'notices', 'noticed', 'noticing',
                    'observe', 'observes', 'observed', 'observing',
                    'prove', 'proves', 'proved', 'proving', 'proven',
                    'realize', 'realizes', 'realized', 'realizing',
                    'recall', 'recalls', 'recalled', 'recalling',
                    'recognize', 'recognizes', 'recognized', 'recognizing',
                    'recollect', 'recollects', 'recollected', 'recollecting',
                    'record', 'records', 'recorded', 'recording',
                    'remember', 'remembers', 'remembered', 'remembering',
                    'see', 'sees', 'saw', 'seeing', 'seen',
                    'show', 'shows', 'showed', 'showing',
                    'signify', 'signifies', 'signified', 'signifying',
                    'submit', 'submits', 'submitted', 'submiting',
                    'testify', 'testifies', 'testified', 'testifying',
                    'understand', 'understands', 'understood', 'understanding'},

        'likelihood': {'appear', 'appears', 'appeared', 'appearing',
                       'assume', 'assumes', 'assumed', 'assuming',
                       'believe', 'believes', 'believed', 'believing',
                       'bet', 'bets', 'bet', 'betting',
                       'conceive', 'conceives', 'conceived', 'conceiving',
                       'consider', 'considers', 'considered', 'considering',
                       'deduce', 'deduces', 'deduced', 'deducing',
                       'detect', 'detects', 'detected', 'detecting',
                       'doubt', 'doubts', 'doubted', 'doubting',
                       'estimate', 'estimates', 'estimated', 'estimating',
                       'figure', 'figures', 'figured', 'figuring',
                       'gather', 'gathers', 'gathered', 'gathering',
                       'guess', 'guesss', 'guessed', 'guessing',
                       'hypothesize', 'hypothesizes', 'hypothesized', 'hypothesizing',
                       'imagine', 'imagines', 'imagined', 'imagining',
                       'indicate', 'indicates', 'indicated', 'indicating',
                       'intend', 'intends', 'intended', 'intending',
                       'perceive', 'perceives', 'perceived', 'perceiving',
                       'postulate', 'postulates', 'postulated', 'postulating',
                       'predict', 'predicts', 'predicted', 'predicting',
                       'presume', 'presumes', 'presumed', 'presuming',
                       'presuppose', 'presupposes', 'presupposed', 'presupposing',
                       'reckon', 'reckons', 'reckoned', 'reckoning',
                       'seem', 'seems', 'seemed', 'seeming',
                       'sense', 'senses', 'sensed', 'sensing',
                       'spectulate', 'spectulates', 'speculated', 'speculating',
                       'suppose', 'supposes', 'supposed', 'supposing',
                       'suspect', 'suspects', 'suspected', 'suspecting',
                       'think', 'thinks', 'thought', 'thinking',
                       'wager', 'wagers', 'wagered', 'wagering'},

        'speechact': {'add', 'adds', 'added', 'adding',
                      'advise', 'advises', 'advised', 'advising',
                      'allege', 'alleges', 'alleged', 'alleging',
                      'answer', 'answers', 'answered', 'answering',
                      'argue', 'argues', 'argued', 'arguing',
                      'ask', 'asks', 'asked', 'asking',
                      'assure', 'assures', 'assured', 'assuring',
                      'beg', 'begs', 'begged', 'begging',
                      'charge', 'charges', 'charged', 'charging',
                      'claim', 'claims', 'claimed', 'claiming',
                      'confess', 'confesses', 'confessed', 'confessing',
                      'confide', 'confides', 'confided', 'confiding',
                      'contend', 'contends', 'contended', 'contending',
                      'convey', 'conveys', 'conveyed', 'conveying',
                      'convince', 'convinces', 'convinced', 'convincing',
                      'decline', 'declines', 'declined', 'declining',
                      'deny', 'denies', 'denied', 'denying',
                      'emphasize', 'emphasizes', 'emphasized', 'emphasizing',
                      'explain', 'explains', 'explained', 'explaining',
                      'express', 'expresses', 'expressed', 'expressing',
                      'hear', 'hears', 'heard', 'hearing',
                      'persuade', 'persuades', 'persuaded', 'persuading',
                      'petition', 'petitions', 'petitioned', 'petitioning',
                      'phone', 'phones', 'phoned', 'phoning',
                      'pray', 'prays', 'prayed', 'praying',
                      'proclaim', 'proclaims', 'proclaimed', 'proclaiming',
                      'propose', 'proposes', 'proposed', 'proposing',
                      'protest', 'protests', 'protested', 'protesting',
                      'prove', 'proves', 'proved', 'proving',
                      'reassure', 'reassures', 'reassured', 'reassuring',
                      'remind', 'reminds', 'reminded', 'reminding',
                      'reply', 'replys', 'replied', 'replying',
                      'report', 'reports', 'reported', 'reporting',
                      'request', 'requests', 'requested', 'requesting',
                      'respond', 'responds', 'responded', 'responding',
                      'reveal', 'reveals', 'revealed', 'revealing',
                      'say', 'says', 'said', 'saying',
                      'shout', 'shouts', 'shouted', 'shouting',
                      'show', 'shows', 'showed', 'showing',
                      'state', 'states', 'stated', 'stating',
                      'stress', 'stresses', 'stressed', 'stressing',
                      'swear', 'swears', 'swore', 'swearing', 'sworn',
                      'teach', 'teachs', 'taught', 'teaching',
                      'telephone', 'telephones', 'telephoned', 'telephoning',
                      'tell', 'tells', 'told', 'telling',
                      'urge', 'urges', 'urged', 'urging',
                      'vow', 'vows', 'vowed', 'vowing',
                      'warn', 'warns', 'warned', 'warning',
                      'whisper', 'whispers', 'whispered', 'whispering',
                      'wire', 'wires', 'wired', 'wiring',
                      'write', 'writes', 'wrote', 'writing', 'written'},

        'cognition': {'assume', 'assumes', 'assumed', 'assuming',
                      'believe', 'believes', 'believed', 'believing',
                      'consider', 'considers', 'considered', 'considering',
                      'estimate', 'estimates', 'estimated', 'estimating',
                      'expect', 'expects', 'expected', 'expecting',
                      'feel', 'feels', 'felt', 'feeling',
                      'find', 'finds', 'found', 'finding',
                      'forget', 'forgets', 'forgot', 'forgetting',
                      'hear', 'hears', 'heard', 'hearing',
                      'imagine', 'imagines', 'imagined', 'imagining',
                      'judge', 'judges', 'judged', 'judging',
                      'know', 'knows', 'knew', 'knowing',
                      'learn', 'learns', 'learned', 'learning', 'learnt',
                      'presume', 'presumes', 'presumed', 'presuming',
                      'pretend', 'pretends', 'pretended', 'pretending',
                      'remember', 'remembers', 'remembered', 'remembering',
                      'see', 'sees', 'saw', 'seeing', 'seen',
                      'suppose', 'supposes', 'supposed', 'supposing',
                      'take', 'takes', 'took', 'taking',
                      'think', 'thinks', 'thought', 'thinking',
                      'trust', 'trusts', 'trusted', 'trusting',
                      'understand', 'understands', 'understood', 'understanding',
                      'watch', 'watchs', 'watched', 'watching'},

        'desire': {'agree', 'agrees', 'agreed', 'agreeing',
                   'aim', 'aims', 'aimed', 'aiming',
                   'bear', 'bears', 'bore', 'bearing', 'born',
                   'care', 'cares', 'cared', 'caring',
                   'choose', 'chooses', 'choosed', 'choosing',
                   'consent', 'consents', 'consented', 'consenting',
                   'dare', 'dares', 'dared', 'daring',
                   'decide', 'decides', 'decided', 'deciding',
                   'design', 'designs', 'designed', 'designing',
                   'desire', 'desires', 'desired', 'desiring',
                   'dread', 'dreads', 'dreaded', 'dreading',
                   'hate', 'hates', 'hated', 'hating',
                   'hesitate', 'hesitates', 'hesitated', 'hesitating',
                   'hope', 'hopes', 'hoped', 'hoping',
                   'intend', 'intends', 'intended', 'intending',
                   'like', 'likes', 'liked', 'liking',
                   'long', 'longs', 'longed', 'longing',
                   'look', 'looks', 'looked', 'looking',
                   'love', 'loves', 'loved', 'loving',
                   'mean', 'means', 'meant', 'meaning',
                   'need', 'needs', 'needed', 'needing',
                   'plan', 'plans', 'planned', 'planing',
                   'prefer', 'prefers', 'preferred', 'preferring',
                   'prepare', 'prepares', 'prepared', 'preparing',
                   'refuse', 'refuses', 'refused', 'refusing',
                   'regret', 'regrets', 'regretted', 'regretting',
                   'resolve', 'resolves', 'resolved', 'resolving',
                   'schedule', 'schedules', 'scheduled', 'scheduling',
                   'stand', 'stands', 'standed', 'standing',
                   'threaten', 'threatens', 'threatened', 'threatening',
                   'volunteer', 'volunteers', 'volunteered', 'volunteering',
                   'wait', 'waits', 'waited', 'waiting',
                   'want', 'wants', 'wanted', 'wanting',
                   'wish', 'wishes', 'wished', 'wishing'},

        'causative': {'afford', 'affords', 'afforded', 'affording',
                      'allow', 'allows', 'allowed', 'allowing',
                      'appoint', 'appoints', 'appointed', 'appointing',
                      'arrange', 'arranges', 'arranged', 'arranging',
                      'assist', 'assists', 'assisted', 'assisting',
                      'attempt', 'attempts', 'attempted', 'attempting',
                      'authorize', 'authorizes', 'authorized', 'authorizing',
                      'bother', 'bothers', 'bothered', 'bothering',
                      'cause', 'causes', 'caused', 'causing',
                      'compel', 'compels', 'compelled', 'complelling',
                      'counsel', 'counsels', 'counselled', 'counselling',
                      'defy', 'defies', 'defied', 'defying',
                      'deserve', 'deserves', 'deserved', 'deserving',
                      'drive', 'drives', 'drove', 'driving', 'driven',
                      'elect', 'elects', 'elected', 'electing',
                      'enable', 'enables', 'enabled', 'enabling',
                      'encourage', 'encourages', 'encouraged', 'encouraging',
                      'endeavor', 'endeavors', 'endeavored', 'endeavoring',
                      'entitle', 'entitles', 'entitled', 'entitling',
                      'fail', 'fails', 'failed', 'failing',
                      'forbid', 'forbids', 'forbade', 'forbiding', 'forbad',
                      'force', 'forces', 'forced', 'forcing',
                      'get', 'gets', 'got', 'getting', 'gotten',
                      'help', 'helps', 'helped', 'helping',
                      'inspire', 'inspires', 'inspired', 'inspiring',
                      'instruct', 'instructs', 'instructed', 'instructing',
                      'lead', 'leads', 'led', 'leading',
                      'leave', 'leaves', 'left', 'leaving',
                      'make', 'makes', 'made', 'making',
                      'manage', 'manages', 'managed', 'managing',
                      'oblige', 'obliges', 'obliged', 'obliging',
                      'order', 'orders', 'ordered', 'ordering',
                      'permit', 'permits', 'permitted', 'permitting',
                      'persuade', 'persuades', 'persuaded', 'persuading',
                      'plan', 'plans', 'planned', 'planning',
                      'promise', 'promises', 'promised', 'promising',
                      'prompt', 'prompts', 'prompted', 'prompting',
                      'raise', 'raises', 'raised', 'raising',
                      'require', 'requires', 'required', 'requiring',
                      'seek', 'seeks', 'seeked', 'seeking',
                      'strive', 'strives', 'strived', 'striving', 'striven',
                      'struggle', 'struggles', 'struggled', 'struggling',
                      'summon', 'summons', 'summoned', 'summoning',
                      'tempt', 'tempts', 'tempted', 'tempting',
                      'try', 'tries', 'tried', 'trying',
                      'venture', 'ventures', 'ventured', 'venturing',
                      'wish', 'wishs', 'wished', 'wishing'},

        'probability': {'appear', 'appears', 'appearing', 'appeared',
                        'come', 'comes', 'coming', 'came',
                        'happen', 'happens', 'happening', 'happened',
                        'seem', 'seems', 'seeming', 'seemed',
                        'tend', 'tends', 'tending', 'tended'},
    },

    'adjective_types': {
        'attitude': {'acceptable', 'adamant', 'advisable', 'afraid', 'alarmed', 'amazed', 'amazing', 'amused',
                     'angrier', 'angriest', 'angry', 'annoyed', 'annoying', 'anomalous', 'appropriate', 'ashtonished',
                     'ashtonishing', 'aware', 'awful', 'best', 'better', 'careful', 'carefuller', 'carefulest',
                     'conceivable', 'concerned', 'critical', 'crucial', 'curious', 'depressed', 'desirable',
                     'disappointed', 'disappointing', 'dissatisfied', 'distressed', 'disturbed', 'dreadful',
                     'embarrasing', 'encouraged', 'essential', 'extraordinary', 'fitting', 'fortunate', 'frightened',
                     'frightening', 'funnier', 'funniest', 'funny', 'glad', 'gladder', 'gladdest', 'good', 'grateful',
                     'great', 'greater', 'greatest', 'happier', 'happiest', 'happy', 'hopeful', 'horrible', 'hurt',
                     'imperative', 'incidental', 'inconceivable', 'incredible', 'indisputable', 'interesting', 'ironic',
                     'irritated', 'irritating', 'luckier', 'luckiest', 'lucky', 'mad', 'madder', 'maddest', 'natural',
                     'neat', 'neater', 'neatest', 'necessary', 'nice', 'nicer', 'nicest', 'notable', 'noteworthy',
                     'noticeable', 'obligatory', 'odd', 'odder', 'oddest', 'okay', 'paradoxical', 'peculiar', 'pleased',
                     'preferable', 'reassured', 'relieved', 'ridiculous', 'sad', 'sadder', 'saddest', 'satisfied',
                     'sensible', 'shocked', 'shocking', 'sillier', 'silliest', 'silly', 'sorrier', 'sorriest', 'sorry',
                     'strange', 'stranger', 'strangest', 'stupid', 'stupider', 'stupidest', 'sufficient', 'surprised',
                     'surprising', 'thankful', 'tragic', 'typical', 'unacceptable', 'unaware', 'uncomfortable',
                     'understandable', 'unfair', 'unfortunate', 'unhappier', 'unhappiest', 'unhappy', 'unlucky',
                     'unthinkable', 'untypical', 'unusual', 'upset', 'upsetting', 'vital', 'wonderful', 'worried'},

        'factive': {'accepted', 'apparent', 'certain', 'clear', 'clearer', 'clearest', 'confident', 'convinced',
                    'correct', 'evident', 'false', 'falser', 'falsest', 'impossible', 'inevitable', 'obvious', 'plain',
                    'plainer', 'plainest', 'positive', 'proved', 'right', 'righter', 'rightest', 'sure', 'surer',
                    'surest', 'true', 'truer', 'truest', 'well-known'},

        'likelihood': {'doubtful', 'likelier', 'likeliest', 'likely', 'possible', 'probable', 'unlikelier',
                       'unlikeliest', 'unlikely'},

        'certainty': {'apt', 'apter', 'aptest', 'certain', 'due', 'guaranteed', 'liable', 'likely', 'prone', 'sure',
                      'surer', 'surest', 'unlikely'},

        'ability': {'able', 'abler', 'ablest', 'anxious', 'bound', 'careful', 'competent', 'determined', 'disposed',
                    'doomed', 'eager', 'eligible', 'fit', 'fitter', 'fittest', 'greedier', 'greediest', 'greedy',
                    'hesitant', 'inclined', 'insufficient', 'keen', 'keener', 'keenest', 'loath', 'obliged', 'prepared',
                    'quick', 'quicker', 'quickest', 'readier', 'readiest', 'ready', 'reluctant', 'set', 'slow',
                    'slower', 'slowest', 'sufficient', 'unable', 'unwilling', 'welcome', 'willing'},

        'personal_affective': {'afraid', 'amazed', 'angrier', 'angriest', 'angry', 'annoyed', 'ashamed', 'astonished',
                               'concerned', 'content', 'curious', 'delighted', 'disappointed', 'disgusted',
                               'embarrased', 'free', 'freer', 'freest', 'furious', 'glad', 'gladder', 'gladdest',
                               'grateful', 'happier', 'happiest', 'happy', 'impatient', 'indignant', 'nervous',
                               'perturbed', 'pleased', 'proud', 'prouder', 'proudest', 'puzzled', 'relieved', 'sorrier',
                               'sorriest', 'sorry', 'surprised', 'worried'},

        'ease': {'difficult', 'easier', 'easiest', 'easy', 'hard', 'harder', 'hardest', 'impossible', 'pleasant',
                 'possible', 'tough', 'tougher', 'toughest', 'unpleasant'},

        'evaluation': {'appropriate', 'awkward', 'bad', 'best', 'better', 'brave', 'braver', 'bravest', 'careless',
                       'convenient', 'crazier', 'craziest', 'crazy', 'criminal', 'cumbersome', 'desirable', 'dreadful',
                       'essential', 'expensive', 'foolhardy', 'fruitless', 'good', 'important', 'improper',
                       'inappropriate', 'interesting', 'logical', 'luckier', 'luckiest', 'lucky', 'mad', 'madder',
                       'maddest', 'necessary', 'nice', 'nicer', 'nicest', 'reasonable', 'right', 'safe', 'safer',
                       'safest', 'sick', 'sicker', 'sickest', 'sillier', 'silliest', 'silly', 'smart', 'smarter',
                       'smartest', 'stupid', 'stupider', 'stupidest', 'surprising', 'unreasonable', 'unseemly',
                       'unwise', 'useful', 'useless', 'vital', 'wise', 'wiser', 'wisest', 'wonderful', 'worse', 'worst',
                       'wrong'}

    },
    # adverb types
    'adverb_types': {

        ##these are in of further attention.  What is currently here is just taken straight from the Biber tagger
        'conjunctive': {'furthermore', 'likewise', 'similarly', 'consequently', 'therefore', 'moreover', 'nonetheless',
                        'notwithstanding', 'hence', 'thus', 'else', 'otherwise', 'namely', 'viz', 'alternatively',
                        'e.g.', 'i.e.', 'conversely', 'instead', 'eg', 'besides', 'nevertheless', 'however', 'rather',
                        'altogether'},

        'amplifier': {'absolutely', 'altogether', 'very', 'completely', 'entirely', 'actually', 'obviously',
                      'extremely', 'fully', 'perfectly', 'thoroughly', 'totally', 'utterly', 'enormously', 'greatly',
                      'highly', 'intensely', 'strongly'},
        # need to add multiword downtoners from Quirk p. 597
        'downtoner': {'almost', 'nearly', 'practically', 'virtually', 'mildly', 'partially', 'partly', 'slightly',
                      'somewhat', 'only', 'merely', 'barely', 'hardly', 'approximately', 'broadly', 'generally',
                      'basically', 'essentially', 'nominally', 'normally', 'primarily', 'principally', 'roughly',
                      'usually', 'scarely'},
        # need to add 'of course' to emphatic ['of', 'course']
        'emphatic': {'just', 'really', 'most', 'so', 'real'},

        'place': {'aboard', 'above', 'abroad', 'across', 'ahead', 'alongside', 'ashore', 'astern', 'away', 'behind',
                  'below', 'beneath', 'beneath', 'beside', 'downhill', 'downstairs', 'downstream', 'east', 'here',
                  'off',
                  'out', 'far', 'hereabouts', 'indoors', 'inland', 'inshore', 'inside', 'locally', 'near', 'nearby',
                  'north', 'nowhere', 'outdoors', 'outside', 'overboard', 'overland', 'overseas', 'south', 'underfoot',
                  'underground', 'underneath', 'uphill', 'upstairs', 'upstream', 'west'},

        'time': {'again', 'early', 'earlier', 'earliest', 'late', 'later', 'latest', 'presently', 'today', 'nowadays',
                 'simultaneously', 'tomorrow', 'tonight', 'soon', 'sooner', 'soonest',
                 'yesterday', 'now', 'afterwards', 'eventually', 'formerly', 'initially', 'immediately',
                 'instantly', 'lately', 'later', 'momentarily', 'once', 'originally', 'previously', 'recently',
                 'shortly', 'subsequently', 'then'},

        'hedges': [['kind', 'of'], ['sort', 'of'], ['almost'], ['maybe']],

        'discourse_particles': {'well', 'now', 'anyway', 'anyhow', 'anyways'},

        # , ['according', 'to'], ['figuratively', 'speaking'], ['speaking', 'truthfully']
        'nonfactive': {'accordingly', 'confidentially', 'frankly', 'generally', 'honestly', 'mainly', 'strictly',
                       'technically', 'typically', 'reportedly'},

        # , ['even', 'worse']
        'attitudinal': {'amazingly', 'astonishingly', 'conveniently', 'curiously', 'disturbingly', 'hopefully',
                        'fortunately', 'importantly', 'ironically', 'regrettably', 'rightly', 'sadly', 'sensibly',
                        'surprisingly', 'unbelievably', 'unfortunately', 'wisely'},
        # , ['in', 'fact'], ['of', 'course'], ['without', 'doubt'], ['no', 'doubt']
        'factive': {'actually', 'always', 'certainly', 'definitely', 'indeed', 'inevitably', 'never', 'obviously',
                    'really', 'undoubtedly'},
        # , ['kind', 'of'], ['most', 'cases'], ['most', 'instances'], ['sort', 'of']
        'likelihood': {'apparently', 'evidently', 'perhaps', 'maybe', 'possibly', 'predictably', 'probably', 'roughly'},

        'other': [['according', 'to'], ['in', 'fact'], ['no', 'doubt'], ['of', 'course'], ['without', 'doubt']]

    },

    # Nominalization suffices
    'nominalization_suffices': {'al', 'an', 'ful', 'er', 'acies', 'acy', 'als', 'ans', 'ance', 'ants', 'ary', 'dom',
                                'doms', 'ee', 'eer', 'ees', 'eers', 'ence', 'ences', 'ers', 'eries', 'ery', 'ese',
                                'ess',
                                'ette', 'fuls', 'hood', 'hoods', 'ism', 'isms', 'ist', 'ists', 'ities', 'ity', 'let',
                                'lets', 'ling', 'lings', 'ment', 'ments', 'ness', 'nesses', 'ship', 'ships', 'ster',
                                'sters', 'tion', 'tions', 'ant', 'age', 'ages', 'ate', 'ates'},

    # Passive post-nominal modifiers
    # Types below come from Longman Corpus
    'vwbn': {

        # suasive
        'vsua': {'drawn', 'ordained', 'undertaken', 'granted', 'ordered', 'resolved', 'resulted', 'requested',
                 'recommended', 'advocated', 'reminded', 'conceded', 'urged', 'proposed', 'persuaded', 'enjoined',
                 'demanded', 'provided', 'intended', 'argued', 'arranged', 'desired', 'advanced'},

        # public
        'vpub': {'emphasized', 'signalled', 'misled', 'answered', 'remarked', 'shouted', 'questioned', 'explained',
                 'reported', 'announced', 'said', 'contended', 'confirmed', 'displayed', 'declared', 'told', 'hinted',
                 'expressed', 'insisted', 'acknowledged', 'stated', 'boasted', 'sworn', 'assured', 'admitted',
                 'maintained', 'informed', 'bought', 'charged', 'recorded', 'alleged', 'emphasised', 'emphasized',
                 'claimed',
                 'drafted', 'guaranteed', 'protested', 'intimated', 'added', 'testified', 'suggested', 'denied',
                 'telephoned', 'honoured', 'pleaded', 'mentioned', 'advised', 'replied', 'predicted', 'objected',
                 'submitted', 'complained', 'promised', 'asked', 'stressed', 'asserted', 'warned', 'agreed'},

        # private
        'vprv': {'presupposed', 'realized', 'learnt', 'hoped', 'confessed', 'imagined', 'recalled', 'noted',
                 'supposed', 'used', 'demonstrated', 'presumed', 'proven', 'accepted', 'saw', 'concerned',
                 'forgotten', 'thought', 'read', 'estimated', 'reflected', 'appreciated', 'perceived', 'observed',
                 'determined', 'decided', 'established', 'known', 'preferred', 'assumed', 'believed', 'realised',
                 'noticed', 'reasoned', 'considered', 'concluded', 'remembered', 'proven', 'sensed', 'held', 'shown',
                 'learned', 'grasped', 'found', 'anticipated', 'expected', 'felt', 'revealed', 'written', 'discovered',
                 'showed', 'heard', 'recognized', 'recognised', 'forgotten', 'suspected', 'feared', 'calculated',
                 'seen',
                 'pretended', 'indicated', 'defined', 'known', 'wished', 'meant', 'reached', 'implied', 'persisted',
                 'understood', 'prayed', 'ensured', 'doubted', 'worried', 'succeeded', 'reckoned', 'judged',
                 'followed'},

    },

    # Tokens from the Longman Corpus that have the vwbn tag more frequently than the vpsv tag
    # The frequency distribution itself is saved as data/vwbn_vpsv_conditional_freq_dist.json
    # But only cases where vwbn are more frequent are in the set here in order to save processing time
    # In the future, it may be better to use the whole dataset to take a more nuanced approach or tag for uncertainty
    # or to redo the dataset to account for register
    # FYI: data/vwbn_vpsv_conditional_freq_dist.json was produced using the following code:
    # >>> from dev_tools import BiberCorpus
    # >>> bc = BiberCorpus('/home/mike/corpora/Longman Spoken and Written Corpus (FOR GRAMMAR PROJECT USE ONLY!)')
    # >>> fd = bc.lex_freq('vwbn', 'vpsv')

    'vwbn_gt_vpsv': {'blossomed', 'compounded', 'fell', 'became', 'saw', 'snared', 'stilled', 'lipsticked', 'idealised',
                     'sued', 'gaudied', 'dislocated', 'revisited', 'lamented', 'allied', 'went', 'came', 'resigned',
                     'collapsed', 'allotted', 'gave', 'began', 'remained', 'blueprint', 'took', 'amounted', 'consisted',
                     'failed', 'contributed', 'connected', 'incurred', 'rumbled', 'pursued', 'grew', 'lavished',
                     'to"sudden', 'emanated', 'surrendered', 'espoused', 'which"employed', 'ensured', 'wrought', 'sank',
                     'dated', 'portrayed', 'elapsed', 'cited', 'demanded', 'embodied', 'surveyed', 'expended',
                     'delineated', 'differed', 'entailed', 'drew', 'ran', 'lay', 'showed', 'appeared', 'won',
                     'prevailed', 'declined', 'engendered', 'rose', 'arose', 'chose', 'emerged', 'converged', 'enacted',
                     'depended', 'reverted', 'insisted', 'attuned', 'problem/need', 'totaled', 'endeavoured', 'figured',
                     'donated', 'invaded', 'enjoyed', 'sown', 'phased', 'being"wasted', 'induced', 'suffered',
                     'emitted', 'sounded', 'fashioned', 'perturbed', 'momen', 'fled', 'plunged', 'opted', 'deviated',
                     'pared', 'knew', 'resulted', 'trebled', 'deteriorated', 'dwarfed', 'flattened', 'rested',
                     'stained', 'vacated', 'emaciated', 'consecrated', 'accorded', 'overcame', 'tended', 'condoned',
                     'perpetrated', 'disrupt', 'creased', 'buffered', 'regimen', 'spaced', 'existed', 'been',
                     'responded', 'occurred', 'belonged', 'wished', 'tempered', 'bonded', 'roughened', 'shorn',
                     'penned', 'abstained', 'predominated', 'overlaid', 'bore', 'persisted', 'of"hidden', 'seemed',
                     'nought', 'scrambled', 'totalled', 'soared', 'complained', 'averaged', 'partitioned', 'wrote',
                     'ensued', 'testified', 'disagreed', 'instilled', 'replied', 'risen', 'partaken', 'unadapted',
                     'strove', 'lasted', 'underlay', 'retaliated', 'withdrew', 'wed', 'fared', 'of"guilt',
                     'criminology"developed', 'inflicted', 'conferred', 'exerted', 'and"bottomed', 'of"given',
                     'constricted', 'arrsnged', 'morphqqevidenced', 'ceased', 'inhabited', 'constraint', 'nonfronted',
                     'unaccented', 'pierced', 'bordered', 'undivided', 'tabulated', 'slung', 'harvested',
                     'unidentified', 'distilled', 'expreienced', 'comtinued', 'pretreated', 'extrapolated', 'prceded',
                     'coincided', 'fertilized', 'bowed', 'coexisted', 'born/hatched', 'lined', 'plummeted',
                     'originated', 'agglutinated', 'rebound', 'shunt', 'rebled', 'malabsorbed', 'crypt', 'pepsinogen',
                     'flanked', 'irradiated', 'retreated', 'nevalainen', 'resembled', 'polyunsaturated', 'percept',
                     'yielded', 'flourished', 'headmen', 'broadcasted', 'undeclared', 'matured', 'behaved', 'woven',
                     'unredressed', 'vested', 'introjected', 'bruised', 'grappled', 'notified', 'spiked', 'laced',
                     'resided', 'oscillated', 'urobilinogen', 'end.point', 'cached', 'are"rounded', 'climbed',
                     'contended', 'kl,k2,...then', 'ovulated', 'sexed', 'unbanded', 'required/produced', 'overlearned',
                     'floating.point', 'disallowed', 'gated', 'rundown', 'spanned', 'hilt', 'sunt', 'zweien',
                     'einfachen', 'that"crossed', 'sewn', 'arrayed', 'looted', 'flocked', 'opined', 'humped',
                     'means"based', 'wore', 'undertook', 'marketwomen', 'despaired', 'parallelled', 'endpoint',
                     'interacted', 'innvervated', 'lacked', 'unasserted', 'unconsidered', 'ered', 'blasted', 'harden',
                     'flowed', 'for"gifted', 'professed', 'sprang', 'undersown', 'ate', 'is"organised', 'starred',
                     'stemmed', 'coshed', 'dassault', 'camouflaged', 'ensnared', 'bequeathed', 'the"enchanted',
                     'articled', 'have"puzzled', 'versed', 'of"green', 'the"objects"concerned', 'subtended', 'liganded',
                     'equivalenced', 'geometry/simulated', 'resupplemented', 'clay/calcite/silt', 'doped', 'midpoint',
                     'steinkern', 'erupted', 'demarcated', 'infrared', 'jammed', 'unstandardized', 'between', 'shone',
                     'proliferated', 'unhindered', 'prograded', 'chopped', 'surfaced', 'mashed', 'nailed', 'sweetened',
                     'clasped', 'perched', 'airfreighted', 'recurred', 'edged', 'orbitalswhen', 'leaved', 'depolarised',
                     'pattrn', 'hasbeen', 'concentratiown', 'white"point', 'need', 'signified', 'available/produced',
                     'sang', 'undressed', 'ren', 'messed', 'shitted', 'flavoured', 'vixen', 'breaded', 'tangled', 'alt',
                     'corned', 'eagled', 'exploded', 'inbetween', 'crazed', 'swelled', 'shooted', 'threw', 'flew',
                     'huddled', 'draped', 'grilled', 'mangled', 'waylaid', 'unsliced', 'crept', 'sprechen', 'explosed',
                     'catapult', 'sheered', 'snowmen', 'setted', 'sobered', 'shook', 'woke', 'ployed', 'cooped',
                     'fathomed', 'tarted', 'grunt', 'glisten', 'unclothed', 'togged', 'skied', 'blew', 'fern', 'kommen',
                     'subscribed', 'salted', 'pickled', 'pranged', 'legged', 'fabled', 'disassociated', 'aint', 'dared',
                     'parallelized', 'fatheaded', 'personalized', 'tattooed', 'rhapsodised', 'upturn', 'dropdown',
                     'ven', 'cheapened', 'destabilized', 'masted', 'brailled', 'niffed', 'wrinkled', 'toffeenosed',
                     'grinned', 'martialled', 'reconditioned', 'pindown', 'pronged', 'retailed', 'proceded', 'whizzed',
                     'rubbished', 'sharpen', 'parachuted', 'reblocked', 'ondssed', 'hoiked', 'blooded', 'unburnt',
                     'forlled', 'encumbered', 'mailshotted', 'downturn', 'vowed', 'dwelled', 'condoled', 'deputized',
                     'roomed', 'reneged', 'belted', 'underlinen', 'malt', 'genned', 'moussed', 'unelected', 'protested',
                     'sniggered', 'noncommissioned', 'anxietyridden', 'instrumented', 'seafront', 'shod', 'conjured',
                     'reprint', 'enumerated', 'cairn', 'umpteen', 'oozed', 'outvoted', 'clouted', 'tern', 'chiselled',
                     'er..consumed', 'noninvolved', 'kindergarten', 'faceted', 'intern', 'aspired', 'flavored',
                     'disheveled', 'unaspirated', 'creamed', 'copped', 'witted', 'teamed', 'scarfed', 'pummeled',
                     '\tthen', 'flirted', 'madwomen', 'knifed', 'prepped', 'birdseed', 'cept', '\tdifficult', 'riled',
                     'parodied', 'thatsupposed', 'he', 'youthought', "who'd", 'everything...when', 'vanished', 'flaunt',
                     'barbequed', 'agen', 'dialed', 'unglued', 'markdown', 'hugged', 'horsedrawn', 'therewhen',
                     'overfed', 'dolt', 'demoed', 'rayed', 'barricaded', 'i', 'rusted', 'reframed', 'thrived',
                     'greatened', 'smooshed', 'deadlocked', 'riveted', 'barked', 'amped', 'spawned', 'letdown',
                     'bighorn', 'brokered', 'crackdown', 'maneuvered', 'joked', 'memorialized', 'belched', 'boycotted',
                     'donned', 'choreographed', 'chairwomen', 'caved', 'surged', 'emblazoned', 'interred', 'crewmen',
                     'polled', 'nestled', 'drizzled', 'handprint', 'napped', 'clapped', 'dangled', 'retorted',
                     'swooped', 'blanketed', 'quintupled', 'bankrupted', 'huffed', 'bullpen', 'embroidered', 'dwindled',
                     'splendored', 'shredded', 'inched', 'lakefront', 'battled', 'foresaw', 'lobbed', 'dissented',
                     'gusted', 'patrolled', 'skirted', 'slumped', 'ducked', 'lingered', 'militiamen', 'thundered',
                     'preconceived', 'shrank', 'hovered', 'rallied', 'barged', 'muttered', 'pounced', 'shivered',
                     'cushioned', 'flitted', 'panned', 'unpunished', 'retooled', 'signaled', 'triumphed', 'spattered',
                     'maintainted', 'prowled', 'ballyhooed', 'grumbled', 'shined', 'glared', 'flashpoint', 'fluttered',
                     'well-developed', 'refocused', 'whistled', 'excercised', 'wandered', 'gowned', 'refaced', 'tugged',
                     'misdated', 'internreted', 'unconditioned', 'foundered', 'proclalsned', 'grudged', 'hummed',
                     'storeyed', 'pervaded', 'officiated', 'welleducated', 'ovnt', 'dreyen', 'kosheren', 'blanked',
                     'brimmed', 'resubmitted', 'mushroomed', 'betokened', 'conduced', 'intervened', 'forbade',
                     'skidded', 'mogulled', 'untracked', 'unopened', 'wielded', 'pokerfaced', 'carpentered', "'unt",
                     'slaughtred', 'aught', 'isfinished', 'resounded', 'limbed', 'unsmirched', 'citified',
                     'unpressurized', 'khalichen', 'mercerized', 'unapproved', 'unanalysed', 'unrequited', 'mehmed',
                     'carbonized', 'receded', "'.'this", 'cabled', 'acquiesced', 'extern', 'unstoried', 'dreadnought',
                     'capitulated', 'eked', 'ked', 'materialized', 'depoliticised', "'i',rn", 'lrint', 'itemsoften',
                     'workrelated', 'riitered', 'wellanalyzed', 'nucleated', 'swarmed', 'wellinformed', 'well-liked',
                     'brained', 'sconed', 'staunched', 'anglicized', 'unespoused', 'dithered', 'unransomed', 'dunned',
                     'tenanted', 'was.delivered', 'earthborn', 'floured', 'rarefied', 'stagnated', 'frostbelt',
                     'areabased', 'flatted', 'untrodden', 'battlemented', 'windswept', 'clean-bred', 'quantized',
                     'unconcealed', 'petered', 'boomed', 'mesmerised', 'covenanted', 'tarboushed', 'footprint',
                     'yawned', 'caroused', 'skinned', 'trickled', 'squatted', 'crenellated', 'skirmished', 'angled',
                     'nudged', 'cased', 'harrowed', 'columned', 'scurried', 'deadfaced', 'quicken', 'unmeasured',
                     'halated', 'photosensitized', 'berated', 'throated', 'bodied', 'engined', 'emigrated',
                     'strongpoint', 'overtook', 'sufficed', 'jockeyed', 'negatived', 'roundheaded', 'sed', 'unsalted',
                     'chromiumplated', 'unpasteurized', 'ceilinged', 'unfrequented', 'coachmen', 'unformed',
                     'unengendered', 'uncanonized', 'expiated', 'yearned', 'sizzled', 'franchised', 'wellborn',
                     'thiamineenriched', 'wellgreased', 'herbseasoned', 'sauted', 'diced', 'blared', 'sortied', 'sped',
                     'trespassed', 'omened', "'-indeed", 'nodded', 'yearsthen', 'creellt', 'afiiiiyfitnded', 'cantered',
                     'galloped', 'glowed', 'tasselled', 'unleavened', 'verbalized', 'totalized', 'sexlinked',
                     'burnished', 'paled', 'soothed', 'embrowned', 'nightmen', 'timekept', 'beingpilloried', 'spired',
                     'communinscribed', 'shafted', 'greenhorn', 'snugged', 'satiated', 'immeshed', 'unfathomed',
                     'countermarched', 'endeavored', 'undiscovered', "'en", 'uncanned', 'presliced', 'comminuted',
                     'argned', 'quarreled', 'geed', 'tenderharted', 'counterfeited', 'clutched', 'befogged',
                     'syllabled', 'suceed', 'slipt', 'pickmen', 'inriched', 'spoyled', 'forteen', 'threteen', 'seaven',
                     'stollen', 'boated', 'meshed', 'disfranchized', 'absconded', 'empty-headed', 'alloted',
                     'skyrocketed', 'jogged', 'clubfooted', 'mustached', 'cowered', 'hagen', 'copulated', 'readdressed',
                     'lshed', 'prosed', 'twicedivided', 'bellshaped', 'vamped', 'unasked', 'it1ept', 'uiunt', 'ied',
                     'helieved', 'obscurantisrn', 'dqqfint', "'lt", 'rechristen', 'wrongheaded', 'velarized', 'ladled',
                     'unimagined', 'batterypowered', 'lacerated', 'bladed', 'doublechecked', 'pivot-pattern',
                     'tasseled', 'atrutonen', 'newlyqqdiscovered', 'unconquered', 'oetween', "'.'that", 'raid.when',
                     'quaked', 'unshackled', 'unforgiven', 'configurated', 'farsighted', 'custombased', 'fizzled',
                     'glamourized', "'e.stern", 'brassfaced', 'keled', 'gabbled', 'pipped', 'decamped', 'atomised',
                     'batsmen', 'unexceeded', 'undefeated', 'scouted', 'crystalized', 'screeched', 'pedailed',
                     'pummelled', 'philibustered', 'midden', 'unlicensed', 'majority.owned', 'writted', 'vied',
                     'marveled', 'tellen', 'unenclosed', 'fine-drawn', 'eyren', 'abasshed', 'downrazed', 'unhedged',
                     'boded', 'longestablished', 'ofblyden', 'weredivided', 'bewailed', 'worseegypt', 'flagellated',
                     'weresummoned', 'whocalled', 'regar:led', 'eiupted', 'thatraged', 'wasdescribed', 'thenserved',
                     'everconceived', 'community,modeled', 'communiqueissued', 'wasconditioned', 'wereincorporated',
                     'wasupgraded', 'hetween', 'principled', 'organizationincorporated', 'officialunited', 'wasbrought',
                     'hisunauthorized', 'hasinfected', 'mqqnt', 'planked', 'necked', 'singlehanded', 'roofed',
                     'nimroded', 'rainswept', 'rouged', 'wheezed', 'hiccuped', 'hadappended', 'wereintended',
                     'bebought', 'ofseamen', 'toadopt', 'hadextended', 'raged', 'hasswallowed', 'whichenjoyed',
                     'nrnhlprn', 'andmanned', 'manyseamen', 'wassubjected', 'thenmounted', 'wereissued', 'wastaken',
                     'thelaundrymen', 'hadbeen', 'itseemed', 'ctrirrlrn', 'theneed', 'hadcommandeered', 'dinned',
                     'werefined', 'andseamen', 'itremained', 'tooprotracted', 'howled', 'delegatesclaimed',
                     'whoattended', 'shipsdevised', 'toaccept', 'half-timbered', 'selfcontained', 'pigged', 'barrelled',
                     'deputised', 'thlt', 'suiiiered', 'bhhorn', 'to0senbliqqqqqqenqqqqen', 'inilncnced', 'crnt',
                     'ea:ercised', 'summareed', 'havered', 'refrained', 'brummagen', 'recommissioned', 'selfproduced',
                     'electronicsrelated', 'beaded', 'unconsecrated', 'bearchildren', 'theunborn', 'ofunmarried',
                     'hadencouraged', 'fromsouthern', 'becomeslegitimatized', 'andwhen', 'himexpelled', 'hestudied',
                     'wasproduced', 'wasdiscredited', 'lectures,extended', 'hadsynthesized', 'liquorcured', 'unsifted',
                     'wasreplaced', 'hetraveled', 'discuiied', 'sicklied', 'wasillustrated', 'formationbetween',
                     'perceptivelylinked', 'broughtincreased', 'insouthern', 'ineastern', 'fondled', 'ofacquired',
                     'heestablished', 'thatdeemphasized', 'weredestroyed', 'thatcontributed', 'establishmentshelped',
                     'probablyrejected', 'theorized', 'anddecided', 'andeven', 'wasthreatened', 'andabandoned',
                     'wasappropriated', 'rebelled', 'vowelled', 'boasted', 'browed', 'cameramen', 'milkmen',
                     'pitchforked', 'hooted', 'undimmed', 'yen', 'footmen', 'sunburnt', 'mildflavoured'}

}
